version: '3'

services:
  app:
    build: .
    ports:
      - "8555:8555"

  nginx:
    image: nginx:latest
    ports:
      - "88:88"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
